### ISSUE TITLE
Inline diagnostics are displayed in insert mode after `f` or `t` motion when flash.nvim is installed

### ISSUE THREAD

**Issue by nowaylifer** [rachartier/tiny-inline-diagnostic.nvim#78] opened 2024-12-19 18:47 UTC
For example, after typing `ct(`:

https://github.com/user-attachments/assets/c19d71ab-6dca-41f7-9db2-c8f3999e7486

There's no such issue with virtual text diagnostics.
Both tiny-inline-diagnostic.nvim and flash.nvim have default config.

**Comment by rachartier** [comment] 2024-12-19 19:51
I cannot reproduce this issue:
![issue_inline](https://github.com/user-attachments/assets/ed97253c-3131-4cbc-8c60-74ac7b783d55)

**Comment by rachartier** [comment] 2024-12-21 01:14
Fixed in 90610e55f438d833c052867d022ff11f27647210

**Closed by rachartier** 2024-12-21 01:14 UTC
